name: Gh-Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # This is the crucial one for git push
      pages: write      # Needed if you are deploying to GitHub Pages

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /power/
          webRenderer: canvaskit
